name: ci-dev

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
   
    
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Check build
        run: npm run build

  request-review:
    runs-on: ubuntu-latest
    needs: build-and-lint
    steps:
      - name: Request review
        run: |
          PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          REVIEWERS='MohitKashyap' # Add GitHub usernames of reviewers separated by commas
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"reviewers\": [$(echo "$REVIEWERS" | sed 's/,/","/g')]}"
